version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DB_URI=mongodb://mongodb:27017/node-js-blog
      - CLOUDINARY_NAME=[CLOUDINARY_NAME]
      - CLOUDINARY_API_KEY=[CLOUDINARY_API_KEY]
      - CLOUDINARY_API_SECRET=[CLOUDINARY_API_SECRET]
      - EXPRESS_SESSION_KEY=[RANDOM]
      - PORT=3000
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: